import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { detectRecursive } from "./codegen/detectRecursive.js";
import { emitCommand } from "./codegen/emit/command.js";
import { emitEvent } from "./codegen/emit/event.js";
import { emitTypeDef } from "./codegen/emit/schema.js";
import { wrapWithSuspend } from "./codegen/emit/suspend.js";
import { loadProtocol } from "./codegen/loadProtocol.js";
import { resolveRefs, type ResolvedDomain } from "./codegen/resolveRefs.js";
import { sortProtocol } from "./codegen/sort.js";
import type { Domain, TypeDef } from "./codegen/types.js";

const HEADER = "// AUTO-GENERATED by scripts/codegen.ts — DO NOT EDIT";
const SHARED_ANCHOR =
  "// AUTO-GENERATED ANCHOR — codegen appends below this line";

const GENERATED_DIR = join(process.cwd(), "src", "generated");
const SHARED_PATH = join(GENERATED_DIR, "Shared.ts");

const fileNameForDomain = (domain: string): string =>
  domain === "Schema" ? "CdpSchema" : domain;

const importPathForDomain = (domain: string): string =>
  `./${fileNameForDomain(domain)}.js`;

const compareText = (left: string, right: string): number =>
  left.localeCompare(right, "en");

// Collect same-domain $ref targets used by a TypeDef (for topo ordering).
const collectLocalRefs = (type: TypeDef): ReadonlySet<string> => {
  const out = new Set<string>();
  const visitRef = (ref: string | undefined): void => {
    if (ref === undefined || ref.includes(".")) {
      return;
    }
    out.add(ref);
  };
  const visitTypeRef = (
    tr:
      | { $ref?: string; items?: { $ref?: string; items?: unknown } }
      | undefined,
  ): void => {
    if (tr === undefined) {
      return;
    }
    visitRef(tr.$ref);
    visitTypeRef(tr.items as never);
  };
  visitTypeRef(type.items);
  if (type.properties !== undefined) {
    for (const prop of type.properties) {
      visitRef(prop.$ref);
      visitTypeRef(prop.items);
    }
  }
  return out;
};

// Topologically sort types within a domain so non-recursive forward refs go
// away. Recursive types (in `recursive`) act as cut points — their edges are
// ignored because they are emitted with Schema.suspend.
const topoSortTypes = (
  types: ReadonlyArray<TypeDef>,
  recursive: ReadonlySet<string>,
): ReadonlyArray<TypeDef> => {
  const byId = new Map<string, TypeDef>();
  for (const t of types) {
    byId.set(t.id, t);
  }
  const visited = new Set<string>();
  const result: Array<TypeDef> = [];
  const visit = (id: string, stack: ReadonlySet<string>): void => {
    if (visited.has(id) || stack.has(id)) {
      return;
    }
    const t = byId.get(id);
    if (t === undefined) {
      return;
    }
    const nextStack = new Set(stack);
    nextStack.add(id);
    if (!recursive.has(id)) {
      // Only follow deps for non-recursive nodes; recursive ones are cut.
      const deps = collectLocalRefs(t);
      const sortedDeps = [...deps].sort(compareText);
      for (const dep of sortedDeps) {
        visit(dep, nextStack);
      }
    }
    visited.add(id);
    result.push(t);
  };
  for (const t of types) {
    visit(t.id, new Set());
  }
  return result;
};

const emitTypeDefForDomain = (
  type: TypeDef,
  domain: string,
  recursive: ReadonlySet<string>,
  cyclicDomains: ReadonlySet<string>,
): string => {
  const base = emitTypeDef(type, domain, cyclicDomains);
  if (!recursive.has(type.id)) {
    return base;
  }
  // emitTypeDef emits: `export const ID = <schema>.annotate({ identifier: "Domain.ID" });`
  // For recursive types, replace with suspend-wrapped form.
  const prefix = `export const ${type.id} = `;
  if (!base.startsWith(prefix)) {
    return base;
  }
  // Strip the trailing semicolon and the `.annotate(...)` tail (wrapWithSuspend
  // adds its own annotate). Find the inner schema before `.annotate({ identifier:`.
  const trimmed = base.slice(prefix.length).replace(/;\s*$/, "");
  const annotateIdx = trimmed.lastIndexOf(".annotate({ identifier:");
  const innerSchema =
    annotateIdx === -1 ? trimmed : trimmed.slice(0, annotateIdx);
  return wrapWithSuspend(type.id, domain, innerSchema, type);
};

const buildDomainFile = (
  resolved: ResolvedDomain,
  recursive: ReadonlySet<string>,
  extractedIdsByDomain: ReadonlyMap<string, ReadonlySet<string>>,
  cyclicDomains: ReadonlySet<string>,
): string => {
  const { domain, imports } = resolved;
  const domainName = domain.domain;
  const extractedForThisDomain =
    extractedIdsByDomain.get(domainName) ?? new Set<string>();

  const lines: Array<string> = [];
  lines.push(HEADER);
  lines.push(`import { Schema } from "effect"`);

  // Cross-domain imports — dedup by `from` (resolveRefs returns one entry per ref).
  const seenImports = new Set<string>();
  for (const imp of imports) {
    if (seenImports.has(imp.from)) {
      continue;
    }
    seenImports.add(imp.from);
    lines.push(
      `import * as ${imp.from} from "${importPathForDomain(imp.from)}"`,
    );
  }

  lines.push("");

  // Types — skip ones extracted to Shared, then topologically sort so
  // forward refs disappear. Cycles (detected by detectRecursive) are broken
  // by suspend-wrapping, so they can sit anywhere in the order.
  const localTypes = domain.types.filter(
    (t) => !extractedForThisDomain.has(t.id),
  );
  const ordered = topoSortTypes(localTypes, recursive);
  for (const type of ordered) {
    lines.push(
      emitTypeDefForDomain(type, domainName, recursive, cyclicDomains),
    );
    lines.push("");
  }

  // Commands.
  for (const command of domain.commands) {
    lines.push(emitCommand(domainName, command, cyclicDomains));
    lines.push("");
  }

  // Events.
  for (const event of domain.events) {
    lines.push(emitEvent(domainName, event, cyclicDomains));
    lines.push("");
  }

  // Collapse trailing blank lines into single newline at EOF.
  while (lines.length > 0 && lines[lines.length - 1] === "") {
    lines.pop();
  }
  lines.push("");
  return lines.join("\n");
};

const buildIndexFile = (domains: ReadonlyArray<Domain>): string => {
  const lines: Array<string> = [HEADER];
  const sorted = [...domains].sort((a, b) => compareText(a.domain, b.domain));
  for (const d of sorted) {
    const namespace = fileNameForDomain(d.domain);
    lines.push(
      `export * as ${namespace} from "${importPathForDomain(d.domain)}"`,
    );
  }
  lines.push("");
  return lines.join("\n");
};

const buildSharedFile = (
  sharedExtracted: ReadonlyArray<{ domain: string; type: TypeDef }>,
): string => {
  const existing = readFileSync(SHARED_PATH, "utf-8");
  const anchorIdx = existing.indexOf(SHARED_ANCHOR);
  if (anchorIdx === -1) {
    throw new Error(`Shared.ts is missing anchor: ${SHARED_ANCHOR}`);
  }
  const head = existing.slice(0, anchorIdx + SHARED_ANCHOR.length);

  const seedIds = new Set<string>();
  const seedRegex = /export const (\w+)/g;
  let match: RegExpExecArray | null = seedRegex.exec(existing);
  while (match !== null) {
    const id = match[1];
    if (id !== undefined) {
      seedIds.add(id);
    }
    match = seedRegex.exec(existing);
  }

  // Deterministic order: by `<domain>.<id>`.
  const sorted = [...sharedExtracted].sort((a, b) =>
    compareText(`${a.domain}.${a.type.id}`, `${b.domain}.${b.type.id}`),
  );

  const blocks: Array<string> = [];
  for (const entry of sorted) {
    if (seedIds.has(entry.type.id)) {
      continue;
    }
    // Recursive by construction (extracted via SCC), so wrap with suspend.
    const innerBase = emitTypeDef(entry.type, entry.domain);
    const prefix = `export const ${entry.type.id} = `;
    let body = innerBase;
    if (innerBase.startsWith(prefix)) {
      const trimmed = innerBase.slice(prefix.length).replace(/;\s*$/, "");
      const annotateIdx = trimmed.lastIndexOf(".annotate({ identifier:");
      const innerSchema =
        annotateIdx === -1 ? trimmed : trimmed.slice(0, annotateIdx);
      body = wrapWithSuspend(
        entry.type.id,
        entry.domain,
        innerSchema,
        entry.type,
      );
    }
    blocks.push(`// ${entry.domain}.${entry.type.id}\n${body}`);
  }

  const tail = blocks.length === 0 ? "" : `\n\n${blocks.join("\n\n")}\n`;
  return `${head}\n${tail}`;
};

const main = (): void => {
  const protocol = sortProtocol(loadProtocol());
  const resolved = resolveRefs(protocol);

  // Group sharedExtracted by domain so we can skip those types when emitting
  // each domain file.
  const extractedByDomain = new Map<string, Set<string>>();
  for (const entry of resolved.sharedExtracted) {
    const set = extractedByDomain.get(entry.domain) ?? new Set<string>();
    set.add(entry.type.id);
    extractedByDomain.set(entry.domain, set);
  }

  let count = 0;
  for (const domain of protocol.domains) {
    const resolvedDomain = resolved.byDomain.get(domain.domain);
    if (resolvedDomain === undefined) {
      continue;
    }
    const recursive = detectRecursive(domain.types);
    const contents = buildDomainFile(
      resolvedDomain,
      recursive,
      extractedByDomain,
      resolved.domainsInCycle,
    );
    const fileName = `${fileNameForDomain(domain.domain)}.ts`;
    writeFileSync(join(GENERATED_DIR, fileName), contents);
    console.log(`Generated: ${fileName}`);
    count += 1;
  }

  writeFileSync(
    join(GENERATED_DIR, "index.ts"),
    buildIndexFile(protocol.domains),
  );
  console.log("Generated: index.ts");

  writeFileSync(SHARED_PATH, buildSharedFile(resolved.sharedExtracted));
  console.log("Generated: Shared.ts");

  console.log(`Codegen complete: ${count} domains`);
};

main();
